spring:
  datasource:
    url: jdbc:postgresql://db:5432/c_payments_db
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8083