# --- Güvenlik ve JWT Ayarları ---
application:
  security:
    jwt:
      # Gizli anahtar aynı kalıyor
      secret-key: 7336763979244226452948404D635166546A576E5A7234753778214125442A47

      # --- SÜRELERİ GÜNCELLEDİK ---
      expiration: 300000            # 5 dakika (eskiden 86400000 idi)
      refresh-token-expiration: 3600000 # 1 saat (eskiden 604800000 idi)
      # ---------------------------